django_auth_adfs-1.15.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
django_auth_adfs-1.15.0.dist-info/LICENSE,sha256=WGMaA474V3mIMiWEkbMc-rCVt-uZvIjF4NqP1AIvNZo,1277
django_auth_adfs-1.15.0.dist-info/METADATA,sha256=t1GQ3og2Nlw5s3M8qGpV2ph_a-iAGk1ebIORTKzwUio,6913
django_auth_adfs-1.15.0.dist-info/RECORD,,
django_auth_adfs-1.15.0.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_auth_adfs-1.15.0.dist-info/WHEEL,sha256=IYZQI976HJqqOpQU6PHkJ8fb3tMNBFjg-Cn-pwAbaFM,88
django_auth_adfs/__init__.py,sha256=1Bo5CRC7tY7wU69FiC93k65bICYiU4o1J3B8MKONPu0,137
django_auth_adfs/__pycache__/__init__.cpython-312.pyc,,
django_auth_adfs/__pycache__/backend.cpython-312.pyc,,
django_auth_adfs/__pycache__/config.cpython-312.pyc,,
django_auth_adfs/__pycache__/drf-urls.cpython-312.pyc,,
django_auth_adfs/__pycache__/drf_urls.cpython-312.pyc,,
django_auth_adfs/__pycache__/exceptions.cpython-312.pyc,,
django_auth_adfs/__pycache__/middleware.cpython-312.pyc,,
django_auth_adfs/__pycache__/rest_framework.cpython-312.pyc,,
django_auth_adfs/__pycache__/signals.cpython-312.pyc,,
django_auth_adfs/__pycache__/urls.cpython-312.pyc,,
django_auth_adfs/__pycache__/views.cpython-312.pyc,,
django_auth_adfs/backend.py,sha256=c18wj5UvViQE-ZYmocz_bS9Iv-6sFdnzRnemlHNxmBg,18442
django_auth_adfs/config.py,sha256=Q6rsJHqVGESEdoLbLRn_H4qeH5c4knh3hKShdpjsSZ8,16376
django_auth_adfs/drf-urls.py,sha256=bBnN1WrgbHoiAs5hTGe-ovmVwwJ4D2xXpYtZVfE8l5U,221
django_auth_adfs/drf_urls.py,sha256=YKH7he1cCDr_eo0kgPJQiJ3kmo1FBS46JzSiBOOqwE0,430
django_auth_adfs/exceptions.py,sha256=yxwKHtDSMnskgBdIQoCWerYVr8sGtIn26GWVVdhA2YU,110
django_auth_adfs/middleware.py,sha256=st8Hx5pHWNcYUNWrCQht3QJqjw6RLQhWyxneTWal0Nw,2249
django_auth_adfs/rest_framework.py,sha256=ajt2iCb02Yqzbv1TAyV3evAnY8z-YEDdsg7zHtx6120,1841
django_auth_adfs/signals.py,sha256=HGD79-dZNEwqVuINoqe6jB_8K1RfuK5Q288RGamTtEU,137
django_auth_adfs/templates/django_auth_adfs/login_failed.html,sha256=1NQ5aCjo7iTLSxy2IXJZbzBp5MaxpfsfQwQ_PDFvgr4,652
django_auth_adfs/urls.py,sha256=4Cec5XbxrAqPHc_N3yMTC_m9UKZXsZktf3rO2niF4Bw,533
django_auth_adfs/views.py,sha256=MHKDCUEvBpNyBCUreX-cCnpp7ThfeoKt_rTt_1CBq9s,5319
